const original_es = {
  "Action": "Acción",
  "ActionDueDate": "Fecha de vencimiento de la acción",
  "ActionRequired": "Se requiere una acción recomendada para esta pregunta",
  "AllowedExtension": "No se puede adjuntar {0} porque esta extensión de archivo no está permitida.",
  "AnswerRequired": "Se requiere una respuesta para esta pregunta",
  "Area": "Área",
  "AuditCapture": "Captura de auditoría",
  "AuditId": "Identificación de auditoría",
  "Auditor": "Auditor",
  "Average": "Promedio",
  "Cancel": "Cancelar",
  "CategoryRequired": "La categoría es obligatoria",
  "Checklist": "Lista de verificación",
  "CodeRequired": "Se requiere código",
  "DueDateBlocked": "No puedes capturar auditorías después de la fecha de vencimiento.",
  "DueDateRequired": "Se requiere una fecha de vencimiento para esta acción",
  "EnterAction": "Ingrese su acción recomendada...",
  "EnterResolvedInPlaceComments": "¿Cómo se resolvió esto?",
  "Explanation": "Explicación",
  "Findings": "Ingrese comentarios sobre su hallazgo...",
  "FindingsRequired": "Se requieren comentarios de búsqueda para esta pregunta",
  "GradedAuditCapture": "Captura de Auditoría Calificada",
  "Location": "Ubicación",
  "MaxNumberFiles": "El archivo cargado excedió el límite de {0} archivos por evidencia. No puedo adjuntar {1}.",
  "Name": "Nombre",
  "Plant": "Planta",
  "Points": "Puntos",
  "ProcessOwner": "Propietario del Proceso",
  "QuestionGroup": "Grupo de preguntas",
  "ReactionPlan": "Plan de Reacción",
  "Required": "Requerido",
  "ResolvedImmediately": "Resuelto inmediatamente",
  "ResolvedInPlaceRequired": "Se requieren comentarios relacionados con la solución",
  "ResponsibleRequired": "Se requiere un propietario de la acción para esta pregunta",
  "Revision": "Revisión",
  "Save": "Enviar",
  "SaveDraft": "Guardar borrador",
  "SelectCategory": "Seleccione una categoría de falla...",
  "SelectCode": "Seleccione un código de error...",
  "SelectFile": "Adjuntar archivo(s)...",
  "SelectResponsible": "Seleccione un Propietario de Acción...",
  "Size": "Tamaño",
  "SizeFile": "El archivo {0} subido supera el límite de {1} MB.",
  "TheFileAlreadyExists": "El archivo {0} ya existe",
  "ThisChecklistIsNoLongerPartOfPlant": "Esta lista de verificación ya no forma parte de la planta: {0}",
  "TotalEvidenceExceed": "El total cargado como evidencia supera el límite de {0} MB. No se puede adjuntar {1}.",
  "TotalPoints": "Puntos Totales",
  "WeightedAuditCapture": "Captura de auditoría ponderada",
  "ZeroFindings": "Zero Hallazgos",
  "ZeroFindingsConfirmation": "¿Está seguro de que no se encontraron problemas y desea guardar los resultados como Cero hallazgos?",
  "Name_Profile": "Nombre",
  "ExplanationAndPlan": "Explicación y Plan",
  "ShowPreviewsAuditsResults": "Mostrar Auditorías Anteriores",
  "G": "[G]",
  "Continue": "Continuar",
  "QuestionGroupDeletedGlobal": "Este grupo de preguntas ya no forma parte del inquilino: {0}",
  "QuestionGroupDeletedLocal": "Este Grupo de Preguntas ya no es parte de la Planta: {0}",
  "Done": "Hecho",
  "Uploading": "Subiendo...",
  "AuditCapture_NcPriorityRequired": "Se requiere una prioridad de incumplimiento",
  "AuditCapture_SelectNcPriority": "Seleccionar prioridad...",
  "AuditCapture_CustomAuditCapture": "Captura de auditoría personalizada",
  "Back": "Atrás",
  "AuditCapture_Preview&amp;Submit": "Vista previa y envío",
  "Attachments": "Adjuntos",
  "Download": "Descargar",
  "QuestionAnswer": "Pregunta Respuesta",
  "Answer": "Respuesta",
  "Yes": "Sí",
  "No": "No",
  "NA": "N\/A",
  "NRI": "No, resuelto en su lugar",
  "Score": "Puntuación",
  "Comments": "Comentarios",
  "AuditDetail_NCPriority": "Prioridad de incumplimiento",
  "FailureCategory": "Categoría de error",
  "FailureCode": "Código de falla",
  "Owner": "Propietario del proceso",
  "Status": "Estado",
  "Code": "Código",
  "Responsible": "Propietario de la acción",
  "DueDate": "Fecha de vencimiento",
  "Description": "Descripción",
  "ResolvedInPlace": "Comentarios resueltos en el lugar",
  "AuditScore": "Puntuación de auditoría",
  "Print": "Imprimir",
  "ConfirmPrint": "Tu auditoría se guardará como borrador antes de abrir la pantalla de impresión. ¿Quieres continuar?",
  "SaveAndExit": "Guardar y Salir",
  "AuditCapture_SaveCreateNewAudit": "Guardar y Crear Nueva Auditoría",
  "AuditCapture_Notes": "Notas",
  "AuditCapture_InSeries": "en serie",
  "EnterComments": "Ingresar comentarios..."
};

export default original_es;