const original_pt = {
  "Action": "Ação",
  "ActionDueDate": "Data de vencimento da ação",
  "ActionRequired": "Uma ação recomendada é necessária para esta pergunta",
  "AllowedExtension": "Não é possível anexar {0} porque esta extensão de arquivo não é permitida.",
  "AnswerRequired": "Uma resposta é necessária para esta pergunta",
  "Area": "Área",
  "AuditCapture": "Captura de auditoria",
  "AuditId": "ID de auditoria",
  "Auditor": "Auditor",
  "Average": "Média",
  "Cancel": "Cancelar",
  "CategoryRequired": "A categoria é obrigatória",
  "Checklist": "Lista de verificação",
  "CodeRequired": "O código é obrigatório",
  "DueDateBlocked": "Você não pode capturar auditorias após a data de vencimento.",
  "DueDateRequired": "É necessária uma data de vencimento para esta ação",
  "EnterAction": "Digite sua ação recomendada...",
  "EnterResolvedInPlaceComments": "Como isso foi resolvido?",
  "Explanation": "Explicação",
  "Findings": "Insira comentários sobre sua descoberta...",
  "FindingsRequired": "Encontrar comentários são necessários para esta pergunta",
  "GradedAuditCapture": "Captura de auditoria graduada",
  "Location": "Localização",
  "MaxNumberFiles": "O arquivo enviado excede o limite de {0} arquivos por evidência. Não é possível anexar {1}.",
  "Name": "Nome",
  "Plant": "Planta",
  "Points": "Pontos",
  "ProcessOwner": "Proprietário do Processo",
  "QuestionGroup": "Grupo de perguntas",
  "ReactionPlan": "Plano de Reação",
  "Required": "Obrigatório",
  "ResolvedImmediately": "Resolvido imediatamente",
  "ResolvedInPlaceRequired": "Comentários relacionados à solução são obrigatórios",
  "ResponsibleRequired": "Um proprietário de ação é necessário para esta pergunta",
  "Revision": "Revisão",
  "Save": "Enviar",
  "SaveDraft": "Salvar Rascunho",
  "SelectCategory": "Selecione uma categoria de falha...",
  "SelectCode": "Selecione um código de falha...",
  "SelectFile": "Anexar arquivo(s)...",
  "SelectResponsible": "Selecione um proprietário da ação...",
  "Size": "Tamanho",
  "SizeFile": "O arquivo {0} carregado excede o limite de {1} MB.",
  "TheFileAlreadyExists": "O arquivo {0} já existe",
  "ThisChecklistIsNoLongerPartOfPlant": "Esta lista de verificação não faz mais parte da Planta: {0}",
  "TotalEvidenceExceed": "O total enviado como evidência excede o limite de {0} MB. Não é possível anexar {1}.",
  "TotalPoints": "Total de Pontos",
  "WeightedAuditCapture": "Captura de auditoria ponderada",
  "ZeroFindings": "Zero Findings",
  "ZeroFindingsConfirmation": "Tem certeza de que nenhum problema foi encontrado e deseja salvar os resultados como Zero Findings?",
  "Name_Profile": "Nome",
  "ExplanationAndPlan": "Explicação e plano",
  "ShowPreviewsAuditsResults": "Mostrar auditorias anteriores",
  "G": "[G]",
  "Continue": "Continuar",
  "QuestionGroupDeletedGlobal": "Este grupo de perguntas não faz mais parte do locatário: {0}",
  "QuestionGroupDeletedLocal": "Este Grupo de Perguntas não faz mais parte da Planta: {0}",
  "Done": "Pronto",
  "Uploading": "Enviando...",
  "AuditCapture_NcPriorityRequired": "É necessária uma prioridade de não conformidade",
  "AuditCapture_SelectNcPriority": "Selecione prioridade...",
  "AuditCapture_CustomAuditCapture": "Captura de auditoria personalizada",
  "Back": "Voltar",
  "AuditCapture_Preview&amp;Submit": "Visualizar e enviar",
  "Attachments": "Anexos",
  "Download": "Baixar",
  "QuestionAnswer": "Resposta à pergunta",
  "Answer": "Responder",
  "Yes": "Sim",
  "No": "Não",
  "NA": "N\/A",
  "NRI": "Não, resolvido no local",
  "Score": "Pontuação",
  "Comments": "Comentários",
  "AuditDetail_NCPriority": "Prioridade de não conformidade",
  "FailureCategory": "Failure Category",
  "FailureCode": "Código de falha",
  "Owner": "Proprietário do Processo",
  "Status": "Estado",
  "Code": "Código",
  "Responsible": "Proprietário da Ação",
  "DueDate": "Data de vencimento",
  "Description": "Descrição",
  "ResolvedInPlace": "Resolvido no local comentários",
  "AuditScore": "Pontuação de auditoria",
  "Print": "Imprimir",
  "ConfirmPrint": "Sua auditoria será salva como rascunho antes de abrir a tela de impressão. Deseja continuar?",
  "SaveAndExit": "Salvar e Sair",
  "AuditCapture_SaveCreateNewAudit": "Salvar e criar nova auditoria",
  "AuditCapture_Notes": "Notas",
  "AuditCapture_InSeries": "em série",
  "EnterComments": "Insira comentários..."
};

export default original_pt;