export const original = {
  Action: "Action",
  ActionDueDate: "Action Due Date",
  ActionRequired: "A recommended action is required for this question",
  AllowedExtension:
    "Can't attach {0} because this file extension is not permitted.",
  AnswerRequired: "An answer is required for this question",
  Area: "Area",
  AuditCapture: "Audit Capture",
  AuditId: "Audit ID",
  Auditor: "Auditor",
  Average: "Average",
  Cancel: "Cancel",
  CategoryRequired: "Category is required",
  Checklist: "Checklist",
  CodeRequired: "Code is required",
  DueDateBlocked: "You cannot capture Audits after Due Date.",
  DueDateRequired: "A due date for this action is required",
  EnterAction: "Enter your recommended action...",
  EnterResolvedInPlaceComments: "How was this resolved?",
  Explanation: "Explanation",
  Findings: "Enter comments about your finding...",
  FindingsRequired: "Finding comments are required for this question",
  GradedAuditCapture: "Graded Audit Capture",
  Location: "Location",
  MaxNumberFiles:
    "Uploaded file exceed the limit of {0} files per evidence. Can\u00b4t attach {1}.",
  Name: "Name",
  Plant: "Plant",
  Points: "Points",
  ProcessOwner: "Process Owner",
  QuestionGroup: "Question Group",
  ReactionPlan: "Reaction Plan",
  Required: "Required",
  ResolvedImmediately: "Resolved immediately",
  ResolvedInPlaceRequired: "Comments related to the solution are required",
  ResponsibleRequired: "An Action Owner is required for this question",
  Revision: "Revision",
  Save: "Submit",
  SaveDraft: "Save Draft",
  SelectCategory: "Select a failure category...",
  SelectCode: "Select a failure code...",
  SelectFile: "Attach File(s)...",
  SelectResponsible: "Select an Action Owner...",
  Size: "Size",
  SizeFile: "The file {0} uploaded exceed the {1} MB limit.",
  TheFileAlreadyExists: "The file {0} already exists",
  ThisChecklistIsNoLongerPartOfPlant:
    "This Checklist is no longer part of Plant: {0}",
  TotalEvidenceExceed:
    "Total uploaded as evidence exceed the {0} MB limit. Can't attach {1}.",
  TotalPoints: "Total Points",
  WeightedAuditCapture: "Weighted Audit Capture",
  ZeroFindings: "Zero Findings",
  ZeroFindingsConfirmation:
    "Are you sure no issues were found and you want to save results as Zero Findings?",
  Name_Profile: "Name",
  ExplanationAndPlan: "Explanation &amp; Plan",
  ShowPreviewsAuditsResults: "Show Previous Audits",
  G: " [G]",
  Continue: "Continue",
  QuestionGroupDeletedGlobal:
    "This Question Group is no longer part of the Tenant: {0}",
  QuestionGroupDeletedLocal:
    "This Question Group is no longer part of the Plant: {0}",
  Done: "Done",
  Uploading: "Uploading...",
  AuditCapture_NcPriorityRequired: "A Non-Conformance Priority is required ",
  AuditCapture_SelectNcPriority: "Select priority...",
  AuditCapture_CustomAuditCapture: "Custom Audit Capture",
  Back: "Back",
  "AuditCapture_Preview&amp;Submit": "Preview &amp; Submit",
  Attachments: "Attachments",
  Download: "Download",
  QuestionAnswer: "Question Answer",
  Answer: "Answer",
  Yes: "Yes",
  No: "No",
  NA: "N/A",
  NRI: "No, Resolved In Place",
  Score: "Score",
  Comments: "Comments",
  AuditDetail_NCPriority: "Non-Conformance Priority",
  FailureCategory: "Failure Category",
  FailureCode: "Failure Code",
  Owner: "Process Owner",
  Status: "Status",
  Code: "Code",
  Responsible: "Action Owner",
  DueDate: "Due Date",
  Description: "Description",
  ResolvedInPlace: "Resolved In Place Comments",
  AuditScore: "Audit Score",
  Print: "Print",
  ConfirmPrint:
    "Your audit will be saved as a draft before opening the print screen. Do you want to continue?",
  SaveAndExit: "Save and Exit",
  AuditCapture_SaveCreateNewAudit: "Save and Create New Audit",
  AuditCapture_Notes: "Notes",
  AuditCapture_InSeries: "in series",
  EnterComments: "Enter comments...",
};
